
#!/bin/bash

# System Information
hostname=$(hostname)
os=$(awk -F= 'NR<=3 && /^NAME|^VERSION/{gsub(/\"/, "", $2); printf "%s ", $2}' /etc/os-release)
uptime=$(uptime -p)

# Hardware Information
cpu=$(sudo lshw -class processor | awk '/product/{gsub("product:",""); gsub(/^[ \t]+|[ \t]+$/, "", $0); print}')
cpuSpeed=$(lshw -class processor | grep -m 1 'capacity' | cut -d ':' -f 2 | sed 's/^[ \t]*//')
ram=$(free -h | awk '/^Mem/{print $2}')
disks=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "NAME")
video=$(lspci | grep -i vga | awk -F '[:()]' '{print $3}')

# Network Information
fqdn=$(hostname -f)
hostAddress=$(hostname -I)
gateway=$(ip route | awk '/default via/{print $3}')
dnsServer=$(cat /etc/resolv.conf | awk '/nameserver/{print $2}')

interface=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $2}' | paste -sd "," -)
ipAddress=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $4}' | cut -d'/' -f1 | paste -sd "," -)

# System Status
users=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
diskSpace=$(df -h | awk '!/Filesystem/{print $4,$6}')
processCount=$(ps aux | wc -l)
loadAverages=$(cat /proc/loadavg | awk '{print $1",",$2",",$3}')
memoryAllocation=$(free -h | awk '/Mem/{print "Total:",$2,"Used:",$3,"Free:",$4}')
listeningPorts=$(ss -tuln | awk 'NR>1{print $4}' | awk -F: '{print $NF}' | sort -n | uniq | tr '\n' ',')
ufwRules=$(sudo ufw status numbered)

cat <<EOF



System Report generated by $USER, $(date)


System Information
_________________
Hostname: $hostname
OS: $os
Uptime: $uptime


Hardware Information
___________________
CPU: $cpu
Speed: $cpuSpeed and  $maxCpuSpeed
RAM: $ram
DISKS:$disks
Video: $video


Network Information
__________________
FQDN: $fqdn
Host Address: $hostAddress
Gateway IP: $gateway
DNS Server: $dnsServer

Interface: $interface
IP Address: $ipAddress


System Status
_____________
Users Logged In: $users
Disk Space:$diskSpace
Process Count: $processCount
Load Averages: $loadAverages
Memory Allocations: $memoryAllocations
Listening Network Ports: $listeningPorts
UFW Rules: $ufwRules


EOF
